# Generated by Django 5.2.1 on 2025-06-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=18)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('스포츠', '스포츠'), ('교육', '교육'), ('사회', '사회'), ('경제', '경제')], max_length=20)),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
